name: Fossmerge Tests

on:
  push:

jobs:
  test-latest:
    name: Integration Tests (latest Fossology)
    runs-on: ubuntu-latest

    container:
      image: python:3.9-slim


    steps:
      - uses: actions/checkout@v1
      - name: Install host dependencies
        run: |
          apt-get -qq update
          apt-get -qq upgrade
          apt-get install -y pandoc
          apt-get install -y python3-lxml
      - name: Install Python dependencies
        run: |
          pip install poetry
          poetry install
      - name: Run tests
        env:
           SKIP_BIG_PANDOC_TESTS: YES
        run: |
          poetry run  coverage run  --source=fossmerge -m pytest -vvv --tb=auto  tests
          poetry run coverage report -m
 


